# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.20240515.6
_src_path: ../copier-py-package/
author_email: randy.syring@level12.io
author_name: Randy Syring
project_name: reqs
py_module: reqs
python_version: '3.12'
script_name: reqs
use_pipx: true
