[build]
dev-mode-dirs = ['src']



[metadata.hooks.requirements_txt]
files = ['requirements/base.txt']


[metadata.hooks.requirements_txt.optional-dependencies]
dev = ['requirements/dev.txt']

[version]
source = 'regex_commit'
path = 'src/reqs/version.py'
